// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCiutuIEOSi_miK4khn2mUl6kb9mx6YPA',
    appId: '1:952094143803:web:3743dedd915237605cf31e',
    messagingSenderId: '952094143803',
    projectId: 'dogdack-4bcfe',
    authDomain: 'dogdack-4bcfe.firebaseapp.com',
    storageBucket: 'dogdack-4bcfe.appspot.com',
    measurementId: 'G-QKGGGY773H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPe-rXbQbfMtzXZDP9nJHmeHf3zx9pBxs',
    appId: '1:952094143803:android:1c34d00f94ceeb3c5cf31e',
    messagingSenderId: '952094143803',
    projectId: 'dogdack-4bcfe',
    storageBucket: 'dogdack-4bcfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqEXMS_a3XiiWXB4PDVgWIgOAI-jpJ-vc',
    appId: '1:952094143803:ios:cd520de938631ff25cf31e',
    messagingSenderId: '952094143803',
    projectId: 'dogdack-4bcfe',
    storageBucket: 'dogdack-4bcfe.appspot.com',
    iosClientId: '952094143803-bfq3snbclbsoatqqfadp4aiiap9k2v1p.apps.googleusercontent.com',
    iosBundleId: 'com.common.pjt.dogdack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqEXMS_a3XiiWXB4PDVgWIgOAI-jpJ-vc',
    appId: '1:952094143803:ios:cd520de938631ff25cf31e',
    messagingSenderId: '952094143803',
    projectId: 'dogdack-4bcfe',
    storageBucket: 'dogdack-4bcfe.appspot.com',
    iosClientId: '952094143803-bfq3snbclbsoatqqfadp4aiiap9k2v1p.apps.googleusercontent.com',
    iosBundleId: 'com.common.pjt.dogdack',
  );
}
